site_name: Staff Mod documentation
repo_url: https://github.com/opekope2/StaffMod
copyright: © 2023-2024 opekope2. Staff Mod is not an official Minecraft product. Not associated with or endorsed by Mojang Studios.
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      experiment: material/test-tube
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - Staff: staff.md
  - For developers: developers.md
  - API docs:
    - Latest: kdoc/latest
    #CI_KDOC_PLACEHOLDER
    - 0.14.0-beta: kdoc/0.14.0-beta
    - 0.13.1-beta: kdoc/0.13.1-beta
    - 0.13.0-beta: kdoc/0.13.0-beta
    - 0.12.0-beta: kdoc/0.12.0-beta
    - 0.11.0-beta.2: kdoc/0.11.0-beta.2
    - 0.11.0-beta: kdoc/0.11.0-beta
    - 0.10.0-beta: kdoc/0.10.0-beta
    - 0.9.0-beta: kdoc/0.9.0-beta
    - 0.8.0-beta: kdoc/0.8.0-beta
    - 0.7.0-beta: kdoc/0.7.0-beta
    - 0.6.0-beta: kdoc/0.6.0-beta
    - 0.5.0-beta: kdoc/0.5.0-beta
    - 0.4.0-beta: kdoc/0.4.0-beta
    - 0.3.0-beta: kdoc/0.3.0-beta
    - 0.2.0-beta: kdoc/0.2.0-beta
    - 0.1.1-alpha.2: kdoc/0.1.1-alpha.2
    - 0.1.1-alpha: kdoc/0.1.1-alpha
  - API docs (Java syntax):
    - Latest: javadoc/latest
    #CI_JAVADOC_PLACEHOLDER
    - 0.14.0-beta: javadoc/0.14.0-beta
    - 0.13.1-beta: javadoc/0.13.1-beta
    - 0.13.0-beta: javadoc/0.13.0-beta
    - 0.12.0-beta: javadoc/0.12.0-beta
    - 0.11.0-beta.2: javadoc/0.11.0-beta.2
    - 0.11.0-beta: javadoc/0.11.0-beta
    - 0.10.0-beta: javadoc/0.10.0-beta
    - 0.9.0-beta: javadoc/0.9.0-beta
    - 0.8.0-beta: javadoc/0.8.0-beta
    - 0.7.0-beta: javadoc/0.7.0-beta
    - 0.6.0-beta: javadoc/0.6.0-beta
    - 0.5.0-beta: javadoc/0.5.0-beta
    - 0.4.0-beta: javadoc/0.4.0-beta
    - 0.3.0-beta: javadoc/0.3.0-beta
    - 0.2.0-beta: javadoc/0.2.0-beta
    - 0.1.1-alpha.2: javadoc/0.1.1-alpha.2
    - 0.1.1-alpha: javadoc/0.1.1-alpha
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.caret
extra_css:
  - stylesheets/admonitions.css
use_directory_urls: false
