site_name: Staff Mod documentation
repo_url: https://github.com/opekope2/StaffMod
copyright: © 2023-2024 opekope2
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - API docs:
    - Latest: kdoc/latest
    #CI_KDOC_PLACEHOLDER
    - 0.1.1-alpha: kdoc/0.1.1-alpha
  - API docs (Java syntax):
    - Latest: javadoc/latest
    #CI_JAVADOC_PLACEHOLDER
    - 0.1.1-alpha: javadoc/0.1.1-alpha
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.caret
use_directory_urls: false
